# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search_index.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'search_index.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12search_index.proto\x12\x0c\x61utocomplete\"|\n\x08Sentence\x12\x13\n\x0bsentence_id\x18\x01 \x01(\x05\x12\x19\n\x11original_sentence\x18\x02 \x01(\t\x12\x1b\n\x13normalized_sentence\x18\x03 \x01(\t\x12\x13\n\x0bsource_path\x18\x04 \x01(\t\x12\x0e\n\x06offset\x18\x05 \x01(\x05\"1\n\x0bPostingList\x12\x0c\n\x04gram\x18\x01 \x01(\t\x12\x14\n\x0csentence_ids\x18\x02 \x03(\x05\"\xdb\x01\n\x0bSearchIndex\x12)\n\tsentences\x18\x01 \x03(\x0b\x32\x16.autocomplete.Sentence\x12+\n\x08unigrams\x18\x02 \x03(\x0b\x32\x19.autocomplete.PostingList\x12*\n\x07\x62igrams\x18\x03 \x03(\x0b\x32\x19.autocomplete.PostingList\x12+\n\x08trigrams\x18\x04 \x03(\x0b\x32\x19.autocomplete.PostingList\x12\x1b\n\x13source_archive_hash\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_index_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTENCE']._serialized_start=36
  _globals['_SENTENCE']._serialized_end=160
  _globals['_POSTINGLIST']._serialized_start=162
  _globals['_POSTINGLIST']._serialized_end=211
  _globals['_SEARCHINDEX']._serialized_start=214
  _globals['_SEARCHINDEX']._serialized_end=433
# @@protoc_insertion_point(module_scope)
